# Generated by Django 5.2.9 on 2025-12-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Unique URL identifier')),
                ('title', models.CharField(max_length=200, verbose_name='Product title')),
                ('image', models.CharField(max_length=50, verbose_name='Product image URL')),
                ('desc', models.TextField(verbose_name='Product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
            ],
        ),
    ]
