# Generated by Django 5.2.9 on 2026-01-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product title')),
                ('surname', models.CharField(max_length=200, verbose_name='Product title')),
                ('email', models.CharField(max_length=200, verbose_name='Product title')),
                ('phone', models.CharField(max_length=200, verbose_name='Product title')),
                ('basket', models.TextField(verbose_name='Product title')),
            ],
        ),
    ]
